package gdac

// curl https://partner.gdac.com/v0.4/public/pairs | jq '.[].pair'
const (
	USDT_KRW  = "USDT/KRW"
	AERGO_KRW = "AERGO/KRW"
	ATOM_BTC  = "ATOM/BTC"
	ATOM_KRW  = "ATOM/KRW"
	ATOMX_KRW = "ATOMX/KRW"
	BCH_KRW   = "BCH/KRW"
	BOA_KRW   = "BOA/KRW"
	BOS_KRW   = "BOS/KRW"
	BSV_KRW   = "BSV/KRW"
	BTC_KRW   = "BTC/KRW"
	COSM_KRW  = "COSM/KRW"
	DASH_KRW  = "DASH/KRW"
	DKA_KRW   = "DKA/KRW"
	ETC_KRW   = "ETC/KRW"
	ETH_KRW   = "ETH/KRW"
	FLETA_KRW = "FLETA/KRW"
	FPT_KRW   = "FPT/KRW"
	GBX_KRW   = "GBX/KRW"
	GT_KRW    = "GT/KRW"
	HDAC_KRW  = "HDAC/KRW"
	HTN_KRW   = "HTN/KRW"
	KLAY_KRW  = "KLAY/KRW"
	KRT_KRW   = "KRT/KRW"
	LTC_KRW   = "LTC/KRW"
	LUNA_KRW  = "LUNA/KRW"
	LUNAX_KRW = "LUNAX/KRW"
	PCH_KRW   = "PCH/KRW"
	PCI_KRW   = "PCI/KRW"
	UPP_KRW   = "UPP/KRW"
	VII_KRW   = "VII/KRW"
	WGP_KRW   = "WGP/KRW"
	XLM_KRW   = "XLM/KRW"
	XRP_KRW   = "XRP/KRW"
)
